[workspace]
resolver = "2"
members = ["core", "fri"]
exclude = ["kate", "kate/recovery"]

[profile.release]
lto = "thin"

[workspace.dependencies]
# Parity
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive", "max-encoded-len"] }
bounded-collections = { version = "0.3", default-features = false }
scale-info = { version = "2", default-features = false, features = ["derive"] }

# Polkadot SDK
binary-merkle-tree = { git = "https://github.com/availproject/polkadot-sdk", rev = "95ce81f7624de3a385fbf77bd954e041730e17f4", default-features = false }
sp-std = { git = "https://github.com/availproject/polkadot-sdk", rev = "95ce81f7624de3a385fbf77bd954e041730e17f4", default-features = false }
sp-trie = { git = "https://github.com/availproject/polkadot-sdk", rev = "95ce81f7624de3a385fbf77bd954e041730e17f4", default-features = false }
sp-runtime = { git = "https://github.com/availproject/polkadot-sdk", rev = "95ce81f7624de3a385fbf77bd954e041730e17f4", default-features = false }
frame-support = { git = "https://github.com/availproject/polkadot-sdk", rev = "95ce81f7624de3a385fbf77bd954e041730e17f4", default-features = false }
sp-runtime-interface = { git = "https://github.com/availproject/polkadot-sdk", rev = "95ce81f7624de3a385fbf77bd954e041730e17f4", default-features = false }
sp-storage = { git = "https://github.com/availproject/polkadot-sdk.git", rev = "95ce81f7624de3a385fbf77bd954e041730e17f4", default-features = false }
sp-debug-derive = { git = "https://github.com/availproject/polkadot-sdk.git", rev = "95ce81f7624de3a385fbf77bd954e041730e17f4", default-features = false }

primitive-types = { version = "0.13.1",  default-features = false, features = ["codec", "scale-info"] }

# Macros
derive_more = { version = "2.1", default-features = false, features = ["constructor", "from", "add", "deref", "mul", "into"] }
static_assertions = { version = "1.1" }
hex-literal = { version = "1.1" }

# Error & Logging
thiserror-no-std = { version = "2.0" }
log = { version = "0.4", default-features = false }
test-case = { version = "3.3" }
proptest = { version = "1" }
criterion = { version = "0.8", default-features = false }

# Serialization
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
const-hex = { version = "1.18", default-features = false, features = ["alloc"] }
serde_json = { version = "1", default-features = false }
impl-serde = { version = "0.5", default-features = false }

# Crypto
hash256-std-hasher = { version = "0.15", default-features = false }
tiny-keccak = { version = "2.0", default-features = false, features = ["keccak"] }
rand = { version = "0.8", features = ["alloc", "small_rng"], default-features = false }
rand_chacha = { version = "0.3", default-features = false }
blake2b_simd = { version = "1.0", default-features = false }
sha2 = { version = "0.10", default-features = false }
sha3 = { version = "0.10", default-features = false }

hash-db = { version = "0.16",  default-features = false }

# fri
binius-prover = { git = "https://github.com/availproject/binius64", rev = "398615c08e56b1b92213156bd6f48418d96f6c49",  default-features = false }
binius-verifier = { git = "https://github.com/availproject/binius64", rev = "398615c08e56b1b92213156bd6f48418d96f6c49",  default-features = false }
binius-math = { git = "https://github.com/availproject/binius64", rev = "398615c08e56b1b92213156bd6f48418d96f6c49",  default-features = false }
binius-field = { git = "https://github.com/availproject/binius64", rev = "398615c08e56b1b92213156bd6f48418d96f6c49",  default-features = false }
binius-transcript = { git = "https://github.com/availproject/binius64", rev = "398615c08e56b1b92213156bd6f48418d96f6c49",  default-features = false }
binius-spartan-prover = { git = "https://github.com/availproject/binius64", rev = "398615c08e56b1b92213156bd6f48418d96f6c49",  default-features = false }
binius-spartan-verifier = { git = "https://github.com/availproject/binius64", rev = "398615c08e56b1b92213156bd6f48418d96f6c49",  default-features = false }
binius-iop = { git = "https://github.com/availproject/binius64", rev = "398615c08e56b1b92213156bd6f48418d96f6c49",  default-features = false }

# Others
rayon = "1.11"
once_cell = "1.21"
num-traits = { version = "0.2", default-features = false }
divan = { version = "0.1" }
digest = { version = "0.10" }
itertools = { version = "0.14" }
trybuild = { version = "1.0" }
lru = { version = "0.16" }


# ETH
# TODO 3.0.0 has issues with some transitive dependency enabling STD in non-STD environment
ethabi-decode = { version = "2.0.0", default-features = false }

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
	'cfg(substrate_runtime)',
] }
