[package]
name = "avail-fri"
version = "0.1.0"
edition = "2021"

[dependencies]
binius-prover = { workspace = true }
binius-verifier = { workspace = true }
binius-math = { workspace = true }
binius-field = { workspace = true }
binius-transcript = { workspace = true }
binius-spartan-prover = { workspace = true, default-features = false, optional = true }
binius-spartan-verifier = { workspace = true, optional = true }
binius-iop = { workspace = true, optional = true }

avail-core = { path = "../core", default-features = false }
blake2b_simd = { workspace = true }
codec  = { workspace = true }
log = { workspace = true, default-features = false }
rayon = { workspace = true, optional = true }
rand_chacha = { workspace = true, default-features = false }
rand = { version = "0.9.1", default-features = false, features = ["std", "std_rng"], optional = true}
serde = { workspace = true, optional = true }
digest = { workspace = true }
itertools = { workspace = true, optional = true }

[dev-dependencies]
avail-core = { path = "../core", default-features = false, features = ["runtime"]}
divan = { workspace = true }
rand = { version = "0.9.1", default-features = false, features = ["std", "std_rng"] }
primitive-types = { workspace = true }

[features]
default = [ "std" ]

# This crate is node-side only currently
std = [
    "avail-core/std",
    "log/std",
    "rand_chacha/std",
    "serde?/std",
    "dep:binius-spartan-prover",
    "dep:binius-spartan-verifier",
    "dep:binius-iop",
    "dep:itertools",
]

# Enable rayon-based parallel code paths
parallel = [ "rayon", "std" ]

bench = [ "std", "rand" ]
testing = []
serde = [ "avail-core/serde", "dep:serde", ]
runtime = [ "avail-core/runtime" ]

[[bench]]
name = "fri_benches"
harness = false
required-features = ["bench"]
