[package]
name = "kate"
version = "0.3.2"
authors = ["Denis Ermolin <denis.ermolin@matic.network>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bls12_381 = { version = "0.3.1", optional = true }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
da-primitives = { path = "../primitives/avail", default-features = false }
dusk-bytes = { version = "0.1.6", default-features = false, optional = true }
dusk-plonk = { git = "https://github.com/maticnetwork/plonk.git", tag = "v0.12.0-polygon-1", optional = true }
frame-support = { version = "4.0.0-dev", default-features = false }
getrandom = { version = "0.2", features = ["js"], optional = true }
hex = { version = "0.4", default-features = false }
log = { version = "0.4.8", optional = true }
num_cpus = { version = "1.13.0", optional = true }
once_cell = { version = "1.9.0", default-features = false }
rand = { version = "0.8.4", default-features = false, optional = true }
rand_chacha = { version = "0.3", default-features = false, optional = true }
rand_core = { version = "0.5", default-features = false }
rayon = { version = "1.5.0", optional = true }
serde = { version = "1.0.121", optional = true, features = ["derive"] }
sp-core = { version = "4.0.0-dev", default-features = false }
sp-std = { version = "4.0.0-dev", default-features = false }
static_assertions = "1.1.0"

[dev-dependencies]
criterion = "0.3.5"
hex-literal = "0.3.4"
itertools = "0.10.3"
kate-proof = { path = "proof", default-features = false }
kate-recovery = { path = "recovery", default-features = false }
proptest = "1.0.0"
test-case = "1.2.3"

[features]
default = ["std"]
alloc = ["dusk-plonk/alloc"]

std = [
	"kate-recovery/std",
	"hex/std",
	"codec/std",
	"alloc",
	"serde",
	"num_cpus",
	"rayon",
	"bls12_381",
	"getrandom",
	"rand",
	"rand_chacha/std",
	"log",
	"dusk-plonk/std",
	"dusk-bytes",
	"sp-std/std",
	"sp-core/std",
	"getrandom/std",
	"rand_core/std",
	"frame-support/std",
	"da-primitives/std",
]
extended-columns = []
maximum-block-size = []

[[bench]]
name = "kzg"
harness = false
